name: ids
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libedit=3.1.20250104
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.8.20
  - python_abi=3.8
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.3.0
  - sqlite=3.49.1
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - diffusers==0.16.1
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - huggingface-hub==0.23.5
      - idna==3.4
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.0
      - numpy==1.24.1
      - pillow==10.2.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.28.1
      - safetensors==0.5.3
      - six==1.17.0
      - sympy==1.13.1
      - tokenizers==0.19.1
      - torch==2.1.1+cu121
      - torchaudio==2.1.1+cu121
      - torchvision==0.16.1+cu121
      - tqdm==4.67.1
      - transformers==4.44.2
      - triton==2.1.0
      - urllib3==1.26.13
      - zipp==3.20.2
